name: Main app CI/CD

on:
  # Run tests on every pull request to any branch
  pull_request:
    branches:
      - '**'

  # Deploy the application when changes are pushed to the main branch
  push:
    branches:
      - main

jobs:
  ossbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install poetry==2.0.1

      - name: Run Unit Tests
        working-directory: ${{ inputs.working-directory }}
        run: |
          poetry install
          poetry run pytest


  scan_malware:
    needs: ossbom
    uses: ./.github/workflows/scan_malware.yml
    permissions:
        id-token: write  # Required for OIDC
        contents: read
        pull-requests: read
    with:
        working-directory: '.'
    secrets:
        OSSPREY_CICD_API_KEY: ${{ secrets.OSSPREY_API_KEY || '' }}

  notify_on_failure:
    needs: [scan_malware]
    if: failure() && github.ref == 'refs/heads/main'  # Only triggers if previous steps fail and we are on the main branch
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Post to Slack on Failure
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN || '' }}
        run: |
            curl -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
              -H "Content-type: application/json" \
              --data '{
                "channel": "#alerts-github",
                "text": "Pipeline Failed: ${{ github.workflow }} in ${{ github.repository }}: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Pipeline Run>"
              }' https://slack.com/api/chat.postMessage
